/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/common/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查接口 - T01 验收依据.
         */
        get: operations["health_api_v1_common_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/test-exception": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Test Exception
         * @description 测试异常接口 - T02 验收依据.
         */
        get: operations["test_exception_api_v1_common_test_exception_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/test-auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test Auth */
        get: operations["test_auth_api_v1_common_test_auth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/test-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test Generate Token */
        get: operations["test_generate_token_api_v1_common_test_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户注册
         * @description 创建新用户账号，返回访问令牌和刷新令牌
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description 通过手机号密码登录，返回双Token（access_token + refresh_token）
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登出
         * @description 吊销当前用户的 refresh_token，使其无法继续使用
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新令牌
         * @description 使用 refresh_token 获取新的 access_token 和 refresh_token（一次性使用）
         */
        post: operations["refresh_token_endpoint_api_v1_auth_refresh_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前用户
         * @description 根据当前Token获取登录用户的基本信息
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户列表
         * @description 分页获取用户列表（支持关键词搜索）。
         *
         *         **权限要求**: user:read（查看用户权限）
         *
         *         **查询参数**:
         *         - page: 页码，默认 1
         *         - page_size: 每页数量，默认 20，最大 100
         *         - keyword: 搜索关键词（匹配用户名/手机号）
         */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /**
         * 创建用户
         * @description 创建新用户账号。
         *
         *         **权限要求**: user:create（创建用户权限）
         *
         *         **适用角色**:
         *         - admin（管理员）- 通常有此权限
         *         - hr（人事）- 可能也有此权限
         *
         *         **不适用角色**:
         *         - teacher（教师）- 不应该能创建用户
         *         - student（学生）- 绝对不能创建用户
         *
         *         **请求示例**:
         *         ```json
         *         {
         *             "username": "zhangsan",
         *             "email": "zhangsan@example.com",
         *             "phone": "13800138000",
         *             "password": "123456",
         *             "role_ids": [1, 2]
         *         }
         *         ```
         */
        post: operations["create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户详情
         * @description 获取指定用户的详细信息。
         *
         *         **权限要求**: user:read
         */
        get: operations["get_user_api_v1_admin_users__user_id__get"];
        /**
         * 更新用户信息
         * @description 更新用户信息（部分更新）。
         *
         *         **权限要求**: user:update AND user:read（必须同时拥有两个权限）
         *
         *         为什么需要两个权限？
         *         - user:update: 允许修改用户数据
         *         - user:read: 编辑前必须能看到当前值（防止盲目修改）
         *
         *         这是一个 **AND 逻辑** 的典型应用场景！
         */
        put: operations["update_user_api_v1_admin_users__user_id__put"];
        post?: never;
        /**
         * 删除用户
         * @description 删除用户（高危操作！）。
         *
         *         **权限要求**: user:delete（专门的删除权限）
         *
         *         安全措施：
         *         1. 需要单独的删除权限（比 update 权限更高级）
         *         2. 不能删除自己的账号
         *         3. 删除后自动清除该用户的权限缓存
         *         4. 记录详细的审计日志
         *
         *         ⚠️ 此权限应该只分配给极少数超级管理员
         */
        delete: operations["delete_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理员后台首页
         * @description 管理员后台首页（Dashboard）。
         *
         *         **角色要求**: admin 或 super_admin（OR 逻辑）
         *
         *         为什么用角色而不是权限？
         *         - Dashboard 是身份概念，不是操作概念
         *         - 只要你是管理员就能看，不关心具体权限
         *         - 更简洁、更直观
         *
         *         对比：
         *         - 用权限：@require_permissions("dashboard:view", "admin:all", ...) 太繁琐
         *         - 用角色：@require_roles("admin", "super_admin") 一行搞定 ✅
         */
        get: operations["admin_dashboard_api_v1_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 系统设置
         * @description 系统设置页面。
         *
         *         **权限要求**: admin:all 或 super:manage（OR 逻辑）
         *
         *         OR 逻辑说明：
         *         - 有 admin:all 权限的普通管理员可以访问
         *         - 有 super:manage 权限的超管也可以访问
         *         - 两者满足其一即可
         *
         *         适用场景：
         *         - 不同级别的管理员都有权访问某些功能
         *         - 但他们的权限来源不同
         */
        get: operations["system_settings_api_v1_admin_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/assign-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 分配用户角色
         * @description 为用户分配或修改角色（双重验证）。
         *
         *         **第一层验证**: 必须是 admin 或 manager 角色
         *         **第二层验证**: 必须有 role:assign 权限
         *
         *         为什么需要双重验证？
         *         - 有些管理员虽然有 admin 角色，但可能没有分配角色的具体权限
         *         - 例如：部门管理员可以看 Dashboard，但不能改角色
         *         - 两层检查更安全、更灵活
         *
         *         执行顺序：
         *         1. 先检查角色（快速失败，避免无谓的数据库查询）
         *         2. 再检查权限（精确控制操作能力）
         */
        post: operations["assign_user_roles_api_v1_admin_users__user_id__assign_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/my-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取我的权限列表
         * @description 获取当前登录用户的完整权限列表。
         *
         *         **用途**:
         *         - 前端根据权限列表动态渲染菜单和按钮
         *         - 如：有 'user:create' 权限才显示"新建"按钮
         *         - 有 'report:view' 权限才显示"报表"菜单项
         *
         *         **特点**:
         *         - 无需额外的权限要求（已登录即可）
         *         - 返回详细的权限信息和缓存状态
         *         - 用于前端权限控制的基础数据源
         *
         *         **前端使用示例** (Vue.js):
         *         ```javascript
         *         // 获取权限列表
         *         const res = await api.get('/admin/my-permissions')
         *         const permissions = res.data.permissions.map(p => p.code)
         *
         *         // 控制按钮显示
         *         <el-button v-if="permissions.includes('user:create')">
         *           新建用户
         *         </el-button>
         *         ```
         */
        get: operations["get_my_permissions_api_v1_admin_my_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/public/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 公开统计数据
         * @description 公开的统计信息（无需登录）。
         *
         *         **权限要求**: 无（完全公开）
         *
         *         适用场景：
         *         - 首页展示的总数据量
         *         - 学校简介中的数字
         *         - 其他不敏感的聚合数据
         */
        get: operations["public_stats_api_v1_admin_public_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量删除用户（高危）
         * @description 批量删除多个用户（极度危险的操作！）。
         *
         *         **角色要求**: super_admin AND security_admin（必须同时拥有两个角色）
         *
         *         为什么用 AND 逻辑？
         *         - 单人误操作风险太高
         *         - 需要两种不同角色的确认
         *         - 类似银行转账需要两个U盾的场景
         *
         *         ⚠️⚠️⚠️ 极度危险操作 ⚠️⚠️⚠️
         *         - 只有同时拥有 super_admin 和 security_admin 角色的用户才能执行
         *         - 会触发审计日志告警
         *         - 建议增加二次确认机制
         */
        post: operations["batch_delete_users_api_v1_admin_users_batch_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户列表
         * @description 分页获取用户列表（支持关键词搜索和状态筛选，需 user:read 权限）
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /**
         * 创建用户
         * @description 创建新用户账号（需 user:create 权限）
         */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户详情
         * @description 获取指定用户的详细信息（需 user:read 权限）
         */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /**
         * 删除用户
         * @description 软删除用户（需 user:delete 权限，不能删除自己）
         */
        delete: operations["delete_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /**
         * 更新用户信息
         * @description 更新用户信息（需 user:update 权限）
         */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改密码
         * @description 用户自己修改密码（需提供旧密码）
         */
        post: operations["change_password_api_v1_users__user_id__password_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重置密码
         * @description 管理员重置用户密码（需 user:reset_password 权限）
         */
        post: operations["reset_password_api_v1_users__user_id__password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户角色
         * @description 获取指定用户的角色列表（需 user:read 权限）
         */
        get: operations["get_user_roles_api_v1_users__user_id__roles_get"];
        /**
         * 分配用户角色
         * @description 为用户分配角色（覆盖式，需 role:assign 权限）
         */
        put: operations["assign_user_roles_api_v1_users__user_id__roles_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取角色列表
         * @description 分页获取角色列表（支持关键词搜索，需 role:read 权限）
         */
        get: operations["list_roles_api_v1_roles_get"];
        put?: never;
        /**
         * 创建角色
         * @description 创建新角色（需 role:create 权限）
         */
        post: operations["create_role_api_v1_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取角色详情
         * @description 获取指定角色的详细信息（需 role:read 权限）
         */
        get: operations["get_role_api_v1_roles__role_id__get"];
        put?: never;
        post?: never;
        /**
         * 删除角色
         * @description 删除角色（需 role:delete 权限，不能删除系统角色）
         */
        delete: operations["delete_role_api_v1_roles__role_id__delete"];
        options?: never;
        head?: never;
        /**
         * 更新角色
         * @description 更新角色信息（需 role:update 权限，不能修改系统角色）
         */
        patch: operations["update_role_api_v1_roles__role_id__patch"];
        trace?: never;
    };
    "/api/v1/roles/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取权限列表
         * @description 获取所有权限列表（支持按模块筛选，需 role:read 权限）
         */
        get: operations["list_permissions_api_v1_roles_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取角色权限
         * @description 获取指定角色的权限列表（需 role:read 权限）
         */
        get: operations["get_role_permissions_api_v1_roles__role_id__permissions_get"];
        /**
         * 分配角色权限
         * @description 为角色分配权限（覆盖式，需 role:assign 权限）
         */
        put: operations["assign_role_permissions_api_v1_roles__role_id__permissions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssignPermissionsRequest
         * @description 分配权限请求体
         */
        AssignPermissionsRequest: {
            /**
             * Permission Ids
             * @description 要分配的权限ID列表
             */
            permission_ids: number[];
        };
        /**
         * AuthResponse
         * @description 认证响应（继承 TokenResponse + 用户信息）
         */
        AuthResponse: {
            /**
             * Access Token
             * @description 访问令牌（有效期 2 小时）
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...access...
             */
            access_token: string;
            /**
             * Refresh Token
             * @description 刷新令牌（有效期 7 天）
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...refresh...
             */
            refresh_token: string;
            /**
             * Token Type
             * @description 令牌类型
             * @default bearer
             * @example bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description 访问令牌过期时间（秒）
             * @default 7200
             * @example 7200
             */
            expires_in: number;
            /** @description 当前用户信息 */
            user: components["schemas"]["UserResponse"];
        };
        /** Body_reset_password_api_v1_users__user_id__password_reset_post */
        Body_reset_password_api_v1_users__user_id__password_reset_post: {
            /**
             * New Password
             * @description 新密码
             */
            new_password: string;
        };
        /**
         * ChangePasswordRequest
         * @description 修改密码请求
         */
        ChangePasswordRequest: {
            /**
             * Old Password
             * @description 旧密码
             */
            old_password: string;
            /**
             * New Password
             * @description 新密码
             */
            new_password: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description 用户登录请求
         */
        LoginRequest: {
            /**
             * Tenant Slug
             * @description 租户标识符
             * @example dance-school
             */
            tenant_slug: string;
            /**
             * Phone
             * @description 手机号码
             * @example 13800138000
             */
            phone: string;
            /**
             * Password
             * @description 密码
             * @example P@ssw0rd123
             */
            password: string;
        };
        /**
         * RefreshTokenRequest
         * @description 刷新令牌请求
         */
        RefreshTokenRequest: {
            /**
             * Refresh Token
             * @description 刷新令牌
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token: string;
        };
        /**
         * RegisterRequest
         * @description 用户注册请求
         */
        RegisterRequest: {
            /**
             * Tenant Slug
             * @description 租户标识符
             * @example dance-school
             */
            tenant_slug: string;
            /**
             * Phone
             * @description 手机号码
             * @example 13800138000
             */
            phone: string;
            /**
             * Password
             * @description 密码（8-20位，需包含大小写字母+数字+特殊字符）
             * @example P@ssw0rd123
             */
            password: string;
            /**
             * Verify Code
             * @description 验证码（4-6位数字或字母）
             * @example 000000
             */
            verify_code: string;
            /**
             * Nickname
             * @description 用户昵称（2-20个字符）
             * @example 小明
             */
            nickname: string;
        };
        /**
         * RoleCreate
         * @description 创建角色请求体
         */
        RoleCreate: {
            /**
             * Code
             * @description 角色代码（唯一标识）
             */
            code: string;
            /**
             * Name
             * @description 角色名称
             */
            name: string;
            /**
             * Description
             * @description 角色描述
             */
            description?: string | null;
            /**
             * Permission Ids
             * @description 初始权限ID列表
             * @default []
             */
            permission_ids: number[] | null;
        };
        /**
         * RoleUpdate
         * @description 更新角色请求体（部分更新）
         */
        RoleUpdate: {
            /**
             * Name
             * @description 角色名称
             */
            name?: string | null;
            /**
             * Description
             * @description 角色描述
             */
            description?: string | null;
        };
        /**
         * TokenResponse
         * @description 令牌响应（双 Token）
         */
        TokenResponse: {
            /**
             * Access Token
             * @description 访问令牌（有效期 2 小时）
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...access...
             */
            access_token: string;
            /**
             * Refresh Token
             * @description 刷新令牌（有效期 7 天）
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...refresh...
             */
            refresh_token: string;
            /**
             * Token Type
             * @description 令牌类型
             * @default bearer
             * @example bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description 访问令牌过期时间（秒）
             * @default 7200
             * @example 7200
             */
            expires_in: number;
        };
        /**
         * UserResponse
         * @description 用户信息响应
         */
        UserResponse: {
            /**
             * Id
             * @description 用户 ID
             * @example 1
             */
            id: number;
            /**
             * Phone
             * @description 手机号（脱敏显示）
             * @example 138****8000
             */
            phone: string;
            /**
             * Nickname
             * @description 用户昵称
             * @example 小明
             */
            nickname: string;
            /**
             * Avatar
             * @description 头像 URL
             * @example https://example.com/avatar.jpg
             */
            avatar?: string | null;
            /**
             * Gender
             * @description 性别
             * @example male
             */
            gender?: string | null;
            /**
             * Status
             * @description 用户状态（1=正常 2=禁用）
             * @example 1
             */
            status: number;
            /**
             * Created At
             * Format: date-time
             * @description 注册时间
             * @example 2026-06-25T10:30:00Z
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * UserCreate
         * @description 创建用户请求体
         */
        app__modules__admin__schemas__UserCreate: {
            /**
             * Username
             * @description 用户名
             */
            username: string;
            /**
             * Email
             * @description 邮箱
             */
            email?: string | null;
            /**
             * Phone
             * @description 手机号
             */
            phone: string;
            /**
             * Is Active
             * @description 是否激活
             * @default true
             */
            is_active: boolean;
            /**
             * Password
             * @description 密码
             */
            password: string;
            /**
             * Role Ids
             * @description 分配的角色ID列表
             * @default []
             */
            role_ids: number[];
        };
        /**
         * UserUpdate
         * @description 更新用户请求体（部分更新）
         */
        app__modules__admin__schemas__UserUpdate: {
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Role Ids */
            role_ids?: number[] | null;
        };
        /**
         * UserCreate
         * @description 创建用户请求体
         */
        app__modules__user__schemas__UserCreate: {
            /**
             * Phone
             * @description 手机号
             */
            phone: string;
            /**
             * Email
             * @description 邮箱
             */
            email?: string | null;
            /**
             * Nickname
             * @description 昵称
             */
            nickname?: string | null;
            /**
             * Real Name
             * @description 真实姓名
             */
            real_name?: string | null;
            /**
             * Avatar Url
             * @description 头像URL
             */
            avatar_url?: string | null;
            /**
             * Gender
             * @description 性别：0未知/1男/2女
             */
            gender?: number | null;
            /**
             * Birthday
             * @description 生日
             */
            birthday?: string | null;
            /**
             * Password
             * @description 密码
             */
            password: string;
            /**
             * Role Ids
             * @description 初始角色ID列表
             * @default []
             */
            role_ids: number[] | null;
        };
        /**
         * UserUpdate
         * @description 更新用户请求体（部分更新）
         */
        app__modules__user__schemas__UserUpdate: {
            /**
             * Phone
             * @description 手机号
             */
            phone?: string | null;
            /**
             * Email
             * @description 邮箱
             */
            email?: string | null;
            /**
             * Nickname
             * @description 昵称
             */
            nickname?: string | null;
            /**
             * Real Name
             * @description 真实姓名
             */
            real_name?: string | null;
            /**
             * Avatar Url
             * @description 头像URL
             */
            avatar_url?: string | null;
            /**
             * Gender
             * @description 性别
             */
            gender?: number | null;
            /**
             * Birthday
             * @description 生日
             */
            birthday?: string | null;
            /**
             * Status
             * @description 状态：0禁用/1启用
             */
            status?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_common_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    test_exception_api_v1_common_test_exception_get: {
        parameters: {
            query: {
                type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_auth_api_v1_common_test_auth_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_generate_token_api_v1_common_test_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description 手机号已存在或租户不存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求参数验证失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description 手机号或密码错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 账号已被禁用 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求参数验证失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description 未登录或Token无效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_endpoint_api_v1_auth_refresh_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description 刷新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Token无效或已过期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token已被吊销 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 获取成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description 未登录或Token无效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                page_size?: number;
                /** @description 搜索关键词 */
                keyword?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__modules__admin__schemas__UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__modules__admin__schemas__UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_dashboard_api_v1_admin_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_settings_api_v1_admin_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_user_roles_api_v1_admin_users__user_id__assign_roles_post: {
        parameters: {
            query: {
                /** @description 要分配的角色ID列表 */
                role_ids: number[];
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 目标用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_permissions_api_v1_admin_my_permissions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_stats_api_v1_admin_public_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    batch_delete_users_api_v1_admin_users_batch_delete_post: {
        parameters: {
            query: {
                /** @description 要删除的用户ID列表 */
                user_ids: number[];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                page_size?: number;
                /** @description 搜索关键词（手机号/昵称/姓名） */
                keyword?: string;
                /** @description 状态筛选：0禁用/1启用 */
                status?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__modules__user__schemas__UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__modules__user__schemas__UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_users__user_id__password_change_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_users__user_id__password_reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_password_api_v1_users__user_id__password_reset_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_roles_api_v1_users__user_id__roles_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_user_roles_api_v1_users__user_id__roles_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 用户ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_v1_roles_get: {
        parameters: {
            query?: {
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                page_size?: number;
                /** @description 搜索关键词（代码/名称） */
                keyword?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_role_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_api_v1_roles__role_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 角色ID */
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_api_v1_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 角色ID */
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_v1_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 角色ID */
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_permissions_api_v1_roles_permissions_get: {
        parameters: {
            query?: {
                /** @description 模块筛选 */
                module?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_permissions_api_v1_roles__role_id__permissions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 角色ID */
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_role_permissions_api_v1_roles__role_id__permissions_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description 角色ID */
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPermissionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
