"""add_wechat_accounts

Revision ID: 01c939988874
Revises: 4bd04b738098
Create Date: 2026-07-31 16:05:57.128993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c939988874'
down_revision: Union[str, Sequence[str], None] = '4bd04b738098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('open_id', sa.String(length=64), nullable=False),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_wechat_accounts_open_id_app_id', 'wechat_accounts', ['open_id', 'app_id'], unique=True)
    op.drop_constraint(op.f('bookings_membership_card_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('classrooms', 'capacity')
    op.drop_column('courses', 'max_capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('max_capacity', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('classrooms', sa.Column('capacity', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('bookings_membership_card_id_fkey'), 'bookings', 'membership_cards', ['membership_card_id'], ['id'], ondelete='SET NULL')
    op.drop_index('uq_wechat_accounts_open_id_app_id', table_name='wechat_accounts')
    op.drop_table('wechat_accounts')
    # ### end Alembic commands ###
