"""add membership card tables

Revision ID: 0281d5735836
Revises: 01c939988874
Create Date: 2026-09-08 12:19:35.815753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0281d5735836'
down_revision: Union[str, Sequence[str], None] = '01c939988874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_card_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('card_type', sa.String(length=20), nullable=False, comment='卡类型'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='售价'),
    sa.Column('total_credits', sa.Integer(), nullable=True, comment='总次数（次卡专用）'),
    sa.Column('validity_days', sa.Integer(), nullable=True, comment='有效天数（从购买日起算）'),
    sa.Column('applicable_course_ids', postgresql.ARRAY(sa.Integer()), nullable=True, comment='适用课程ID列表，NULL表示不限'),
    sa.Column('max_weekly_usage', sa.Integer(), nullable=True, comment='每周最多使用次数，NULL表示不限'),
    sa.Column('description', sa.Text(), nullable=True, comment='产品描述'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_products_tenant_status', 'membership_card_products', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_products_tenant_type', 'membership_card_products', ['tenant_id', 'card_type'], unique=False)
    op.create_index(op.f('ix_membership_card_products_tenant_id'), 'membership_card_products', ['tenant_id'], unique=False)
    op.create_table('membership_card_freezes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=False, comment='会员卡ID'),
    sa.Column('reason', sa.String(length=255), nullable=False, comment='冻结原因'),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False, comment='冻结时间'),
    sa.Column('unfrozen_at', sa.DateTime(timezone=True), nullable=True, comment='解冻时间'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作人ID'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['membership_cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_freezes_card', 'membership_card_freezes', ['tenant_id', 'card_id'], unique=False)
    op.create_index('idx_freezes_created', 'membership_card_freezes', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_membership_card_freezes_tenant_id'), 'membership_card_freezes', ['tenant_id'], unique=False)
    op.create_table('membership_card_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=False, comment='会员卡ID'),
    sa.Column('booking_id', sa.BigInteger(), nullable=True, comment='关联预约ID'),
    sa.Column('operation_type', sa.String(length=20), nullable=False, comment='操作类型'),
    sa.Column('change_amount', sa.Integer(), nullable=False, comment='变动数量（正数增加，负数扣减）'),
    sa.Column('balance_after', sa.Integer(), nullable=False, comment='变动后剩余次数'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作人ID'),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True, comment='幂等键'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['card_id'], ['membership_cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_transactions_booking', 'membership_card_transactions', ['tenant_id', 'booking_id'], unique=False)
    op.create_index('idx_transactions_card', 'membership_card_transactions', ['tenant_id', 'card_id'], unique=False)
    op.create_index('idx_transactions_created', 'membership_card_transactions', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_transactions_idempotency', 'membership_card_transactions', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index(op.f('ix_membership_card_transactions_tenant_id'), 'membership_card_transactions', ['tenant_id'], unique=False)
    op.add_column('membership_cards', sa.Column('product_id', sa.BigInteger(), nullable=True, comment='关联产品ID'))
    op.add_column('membership_cards', sa.Column('applicable_course_ids', postgresql.ARRAY(sa.Integer()), nullable=True, comment='适用课程ID列表（从产品继承）'))
    op.add_column('membership_cards', sa.Column('max_weekly_usage', sa.Integer(), nullable=True, comment='每周使用上限（从产品继承）'))
    op.add_column('membership_cards', sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True, comment='冻结时间'))
    op.add_column('membership_cards', sa.Column('frozen_reason', sa.String(length=255), nullable=True, comment='冻结原因'))
    op.add_column('membership_cards', sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作人ID'))
    op.alter_column('membership_cards', 'student_id',
               existing_type=sa.BIGINT(),
               comment='学员ID',
               existing_nullable=False)
    op.alter_column('membership_cards', 'card_type',
               existing_type=sa.VARCHAR(length=20),
               comment='卡类型（冗余字段）',
               existing_nullable=False)
    op.alter_column('membership_cards', 'total_credits',
               existing_type=sa.INTEGER(),
               comment='总次数',
               existing_nullable=True)
    op.alter_column('membership_cards', 'used_credits',
               existing_type=sa.INTEGER(),
               comment='已使用次数',
               existing_nullable=False)
    op.alter_column('membership_cards', 'valid_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='生效时间',
               existing_nullable=True)
    op.alter_column('membership_cards', 'expire_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='过期时间',
               existing_nullable=True)
    op.alter_column('membership_cards', 'status',
               existing_type=sa.SMALLINT(),
               comment='状态',
               existing_nullable=False)
    op.create_index('idx_cards_expire', 'membership_cards', ['tenant_id', 'expire_at', 'status'], unique=False)
    op.create_index('idx_cards_product', 'membership_cards', ['tenant_id', 'product_id'], unique=False)
    op.create_foreign_key(None, 'membership_cards', 'membership_card_products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'membership_cards', type_='foreignkey')
    op.drop_index('idx_cards_product', table_name='membership_cards')
    op.drop_index('idx_cards_expire', table_name='membership_cards')
    op.alter_column('membership_cards', 'status',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('membership_cards', 'expire_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='过期时间',
               existing_nullable=True)
    op.alter_column('membership_cards', 'valid_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='生效时间',
               existing_nullable=True)
    op.alter_column('membership_cards', 'used_credits',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='已使用次数',
               existing_nullable=False)
    op.alter_column('membership_cards', 'total_credits',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='总次数',
               existing_nullable=True)
    op.alter_column('membership_cards', 'card_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='卡类型（冗余字段）',
               existing_nullable=False)
    op.alter_column('membership_cards', 'student_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='学员ID',
               existing_nullable=False)
    op.drop_column('membership_cards', 'operator_id')
    op.drop_column('membership_cards', 'frozen_reason')
    op.drop_column('membership_cards', 'frozen_at')
    op.drop_column('membership_cards', 'max_weekly_usage')
    op.drop_column('membership_cards', 'applicable_course_ids')
    op.drop_column('membership_cards', 'product_id')
    op.drop_index(op.f('ix_membership_card_transactions_tenant_id'), table_name='membership_card_transactions')
    op.drop_index('idx_transactions_idempotency', table_name='membership_card_transactions', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('idx_transactions_created', table_name='membership_card_transactions')
    op.drop_index('idx_transactions_card', table_name='membership_card_transactions')
    op.drop_index('idx_transactions_booking', table_name='membership_card_transactions')
    op.drop_table('membership_card_transactions')
    op.drop_index(op.f('ix_membership_card_freezes_tenant_id'), table_name='membership_card_freezes')
    op.drop_index('idx_freezes_created', table_name='membership_card_freezes')
    op.drop_index('idx_freezes_card', table_name='membership_card_freezes')
    op.drop_table('membership_card_freezes')
    op.drop_index(op.f('ix_membership_card_products_tenant_id'), table_name='membership_card_products')
    op.drop_index('idx_products_tenant_type', table_name='membership_card_products')
    op.drop_index('idx_products_tenant_status', table_name='membership_card_products')
    op.drop_table('membership_card_products')
    # ### end Alembic commands ###
