"""init all tables

Revision ID: 4bd04b738098
Revises: 
Create Date: 2026-06-23 17:08:42.954232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd04b738098'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_tenant_created', 'audit_logs', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_user_created', 'audit_logs', ['tenant_id', 'user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('equipment', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_tenant_id'), 'classrooms', ['tenant_id'], unique=False)
    op.create_index('uq_classrooms_tenant_name', 'classrooms', ['tenant_id', 'name'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('max_capacity', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('required_credits', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_courses_tenant_category', 'courses', ['tenant_id', 'category'], unique=False)
    op.create_index('idx_courses_tenant_status', 'courses', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_index('uq_roles_tenant_code', 'roles', [sa.literal_column('COALESCE(tenant_id, 0)'), 'code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('platform_role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_users_tenant_status', 'users', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('uq_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.create_index('uq_users_tenant_phone', 'users', ['tenant_id', 'phone'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('course_schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('classroom_id', sa.BigInteger(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('booked_count', sa.SmallInteger(), nullable=False),
    sa.Column('booking_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('booked_count <= capacity AND booked_count >= 0', name='chk_schedule_capacity'),
    sa.CheckConstraint('end_at > start_at', name='chk_schedule_time'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_schedules_classroom_start', 'course_schedules', ['tenant_id', 'classroom_id', 'start_at'], unique=False)
    op.create_index('idx_schedules_course', 'course_schedules', ['course_id'], unique=False)
    op.create_index('idx_schedules_teacher_start', 'course_schedules', ['tenant_id', 'teacher_id', 'start_at'], unique=False)
    op.create_index('idx_schedules_tenant_start', 'course_schedules', ['tenant_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_course_schedules_tenant_id'), 'course_schedules', ['tenant_id'], unique=False)
    op.create_table('membership_cards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('used_credits', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_cards_student', 'membership_cards', ['tenant_id', 'student_id', 'status'], unique=False)
    op.create_index(op.f('ix_membership_cards_tenant_id'), 'membership_cards', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_orders_status_created', 'orders', ['tenant_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_orders_user', 'orders', ['tenant_id', 'user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_student_profiles_tenant', 'student_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_tenant_id'), 'student_profiles', ['tenant_id'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialties', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('years_of_experience', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_teacher_profiles_tenant', 'teacher_profiles', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_teacher_profiles_tenant_id'), 'teacher_profiles', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('membership_card_id', sa.BigInteger(), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=255), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_card_id'], ['membership_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['course_schedules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_bookings_schedule', 'bookings', ['tenant_id', 'schedule_id', 'status'], unique=False)
    op.create_index('idx_bookings_student', 'bookings', ['tenant_id', 'student_id', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_index('uq_bookings_schedule_student_active', 'bookings', ['schedule_id', 'student_id'], unique=True, postgresql_where=sa.text('status IN (1, 3, 4)'))
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('out_trade_no', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('out_trade_no'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_payments_order', 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index('idx_payments_order', table_name='payments')
    op.drop_table('payments')
    op.drop_index('uq_bookings_schedule_student_active', table_name='bookings', postgresql_where=sa.text('status IN (1, 3, 4)'))
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index('idx_bookings_student', table_name='bookings')
    op.drop_index('idx_bookings_schedule', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_teacher_profiles_tenant_id'), table_name='teacher_profiles')
    op.drop_index('idx_teacher_profiles_tenant', table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_student_profiles_tenant_id'), table_name='student_profiles')
    op.drop_index('idx_student_profiles_tenant', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index('idx_orders_user', table_name='orders')
    op.drop_index('idx_orders_status_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_membership_cards_tenant_id'), table_name='membership_cards')
    op.drop_index('idx_cards_student', table_name='membership_cards')
    op.drop_table('membership_cards')
    op.drop_index(op.f('ix_course_schedules_tenant_id'), table_name='course_schedules')
    op.drop_index('idx_schedules_tenant_start', table_name='course_schedules')
    op.drop_index('idx_schedules_teacher_start', table_name='course_schedules')
    op.drop_index('idx_schedules_course', table_name='course_schedules')
    op.drop_index('idx_schedules_classroom_start', table_name='course_schedules')
    op.drop_table('course_schedules')
    op.drop_index('uq_users_tenant_phone', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_users_tenant_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('idx_users_tenant_status', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_roles_tenant_code', table_name='roles')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_index('idx_courses_tenant_status', table_name='courses', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_courses_tenant_category', table_name='courses')
    op.drop_table('courses')
    op.drop_index('uq_classrooms_tenant_name', table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_tenant_id'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('permissions')
    op.drop_index('idx_audit_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
