"""add membership_card_id to orders table

Revision ID: 57aeb9dcf020
Revises: 0281d5735836
Create Date: 2026-09-08 12:58:40.596692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57aeb9dcf020'
down_revision: Union[str, Sequence[str], None] = '0281d5735836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('membership_card_id', sa.BigInteger(), nullable=True, comment='关联会员卡ID（购买次卡时生成）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'membership_card_id')
    # ### end Alembic commands ###
