"""add_phont_to_users

Revision ID: c17b284c3335
Revises: add_schedule_cancel_fields
Create Date: 2026-09-13 16:35:38.722431

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c17b284c3335"
down_revision: str | Sequence[str] | None = "add_schedule_cancel_fields"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course_schedules",
        "cancel_reason",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="取消原因",
        existing_nullable=True,
    )
    op.alter_column(
        "course_schedules",
        "cancelled_by",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="取消操作人ID",
        existing_nullable=True,
    )
    op.alter_column(
        "course_schedules",
        "cancelled_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="取消时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_course_types_tenant_id"), "course_types", ["tenant_id"], unique=False)
    op.create_foreign_key(
        None, "course_types", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(
        "idx_products_deleted_at", "membership_card_products", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_products_deleted_at", table_name="membership_card_products")
    op.drop_constraint(None, "course_types", type_="foreignkey")
    op.drop_index(op.f("ix_course_types_tenant_id"), table_name="course_types")
    op.alter_column(
        "course_schedules",
        "cancelled_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="取消时间",
        existing_nullable=True,
    )
    op.alter_column(
        "course_schedules",
        "cancelled_by",
        existing_type=sa.BIGINT(),
        comment="取消操作人ID",
        existing_nullable=True,
    )
    op.alter_column(
        "course_schedules",
        "cancel_reason",
        existing_type=sa.TEXT(),
        comment="取消原因",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
