"""数据库迁移0917

Revision ID: ef07aa8bcff8
Revises: 448a38329d65
Create Date: 2026-09-17 20:58:36.082617

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef07aa8bcff8"
down_revision: str | Sequence[str] | None = "448a38329d65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course_categories",
        "name",
        existing_type=sa.VARCHAR(length=50),
        comment="分类名称",
        existing_nullable=False,
    )
    op.alter_column(
        "course_categories",
        "code",
        existing_type=sa.VARCHAR(length=50),
        comment="分类代码",
        existing_nullable=False,
    )
    op.alter_column(
        "course_categories",
        "description",
        existing_type=sa.TEXT(),
        comment="分类描述/介绍",
        existing_nullable=True,
    )
    op.alter_column(
        "course_categories",
        "icon_url",
        existing_type=sa.VARCHAR(length=500),
        comment="分类图标URL",
        existing_nullable=True,
    )
    op.alter_column(
        "course_categories",
        "sort_order",
        existing_type=sa.INTEGER(),
        comment="排序",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "course_categories",
        "status",
        existing_type=sa.SMALLINT(),
        comment="状态：0禁用/1启用",
        existing_nullable=False,
        existing_server_default=sa.text("'1'::smallint"),
    )
    op.alter_column(
        "course_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "course_categories",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_course_categories_tenant_id"), "course_categories", ["tenant_id"], unique=False
    )
    op.drop_constraint(
        op.f("course_categories_tenant_id_fkey"), "course_categories", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "course_categories", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("course_categories", "deleted_at")
    op.drop_index(op.f("idx_cards_card_no"), table_name="membership_cards")
    op.create_unique_constraint(None, "membership_cards", ["card_no"])
    op.alter_column(
        "student_profiles",
        "student_code",
        existing_type=sa.VARCHAR(length=20),
        comment="学员编号：S + yyyyMMdd + 6位随机数",
        existing_comment="学员编号",
        existing_nullable=True,
    )
    op.alter_column(
        "student_profiles",
        "status",
        existing_type=sa.SMALLINT(),
        comment=None,
        existing_comment="状态：0禁用/1启用",
        existing_nullable=False,
        existing_server_default=sa.text("'1'::smallint"),
    )
    op.drop_index(op.f("idx_student_profiles_code"), table_name="student_profiles")
    op.create_index(
        op.f("ix_student_profiles_student_code"), "student_profiles", ["student_code"], unique=True
    )
    op.alter_column(
        "teacher_profiles",
        "teacher_code",
        existing_type=sa.VARCHAR(length=20),
        comment="教师编号：T + yyyyMMdd + 6位随机数",
        existing_comment="教师编号",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_teacher_profiles_code"), table_name="teacher_profiles")
    op.create_index(
        op.f("ix_teacher_profiles_teacher_code"), "teacher_profiles", ["teacher_code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teacher_profiles_teacher_code"), table_name="teacher_profiles")
    op.create_index(
        op.f("idx_teacher_profiles_code"), "teacher_profiles", ["teacher_code"], unique=True
    )
    op.alter_column(
        "teacher_profiles",
        "teacher_code",
        existing_type=sa.VARCHAR(length=20),
        comment="教师编号",
        existing_comment="教师编号：T + yyyyMMdd + 6位随机数",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_student_profiles_student_code"), table_name="student_profiles")
    op.create_index(
        op.f("idx_student_profiles_code"), "student_profiles", ["student_code"], unique=True
    )
    op.alter_column(
        "student_profiles",
        "status",
        existing_type=sa.SMALLINT(),
        comment="状态：0禁用/1启用",
        existing_nullable=False,
        existing_server_default=sa.text("'1'::smallint"),
    )
    op.alter_column(
        "student_profiles",
        "student_code",
        existing_type=sa.VARCHAR(length=20),
        comment="学员编号",
        existing_comment="学员编号：S + yyyyMMdd + 6位随机数",
        existing_nullable=True,
    )
    op.drop_constraint(None, "membership_cards", type_="unique")
    op.create_index(op.f("idx_cards_card_no"), "membership_cards", ["card_no"], unique=True)
    op.add_column(
        "course_categories",
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "course_categories", type_="foreignkey")
    op.create_foreign_key(
        op.f("course_categories_tenant_id_fkey"),
        "course_categories",
        "tenants",
        ["tenant_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_course_categories_tenant_id"), table_name="course_categories")
    op.alter_column(
        "course_categories",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "course_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "course_categories",
        "status",
        existing_type=sa.SMALLINT(),
        comment=None,
        existing_comment="状态：0禁用/1启用",
        existing_nullable=False,
        existing_server_default=sa.text("'1'::smallint"),
    )
    op.alter_column(
        "course_categories",
        "sort_order",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="排序",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "course_categories",
        "icon_url",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="分类图标URL",
        existing_nullable=True,
    )
    op.alter_column(
        "course_categories",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="分类描述/介绍",
        existing_nullable=True,
    )
    op.alter_column(
        "course_categories",
        "code",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="分类代码",
        existing_nullable=False,
    )
    op.alter_column(
        "course_categories",
        "name",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="分类名称",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
